import type {Portrait} from './types.ts'

export const initialPortraits: Array<Portrait> = [
  {
    id: 'goose',
    title: 'His Unbothered Majesty',
    creator: 'Cornelius van Honk',
    description: 'A ruler of impeccable breeding and absolutely no qualifications. His foreign policy consists primarily of hissing.',
    source: '/art/work-0.webp',
    position: [
      -3.6,
      2.5,
      -7.78,
    ],
    rotation: 0,
    width: 2.05,
    height: 2.05,
    hung: true,
    wallId: 'daydream-north',
  },
  {
    id: 'orange',
    title: 'A Slightly Larger Tomorrow',
    creator: 'The Department of Daydreams',
    description: 'The village had asked for a little more sunshine. The universe, as usual, misunderstood the brief.',
    source: '/art/work-1.webp',
    position: [
      0,
      2.65,
      -7.78,
    ],
    rotation: 0,
    width: 2.7,
    height: 2.7,
    hung: true,
    wallId: 'daydream-north',
  },
  {
    id: 'lobster',
    title: 'An Uninvited Tea Guest',
    creator: 'Salvador Deli',
    description: 'The tea is cold. The guest is shellfish. Nobody is having the afternoon they had imagined.',
    source: '/art/work-2.webp',
    position: [
      3.6,
      2.5,
      -7.78,
    ],
    rotation: 0,
    width: 2.05,
    height: 2.05,
    hung: true,
    wallId: 'daydream-north',
  },
  {
    id: 'cloud',
    title: 'Rooted in Absolutely Nothing',
    creator: 'Sylvia Nimbus',
    description: 'A tree with excellent aspirations and a rather relaxed relationship with the ground. The gardener has requested a ladder.',
    source: '/art/work-3.webp',
    position: [
      -7.78,
      2.5,
      -2.8,
    ],
    rotation: 1.570_796_326_794_896_6,
    width: 2.6,
    height: 2.6,
    hung: true,
    wallId: 'daydream-west',
  },
  {
    id: 'astronaut',
    title: 'One Small Step for Lunch',
    creator: 'Captain Marmalade',
    description: 'He came in peace. He stayed for the carbohydrates. Mission control has stopped asking where the baguette came from.',
    source: '/art/extra-0.webp',
    position: [
      7.78,
      2.6,
      -2.8,
    ],
    rotation: -1.570_796_326_794_896_6,
    width: 1.45,
    height: 2.9,
    hung: true,
    wallId: 'daydream-east',
  },
  {
    id: 'jellyfish',
    title: 'The Chandelier Has Opinions',
    creator: 'Aurelia de Medusa',
    description: 'The ballroom lighting is alive, temperamental and not covered by the electrical warranty. Please dance at a respectful distance.',
    source: '/art/extra-1.webp',
    position: [
      19.78,
      2.6,
      -2,
    ],
    rotation: -1.570_796_326_794_896_6,
    width: 1.45,
    height: 2.9,
    hung: true,
    wallId: 'afterhours-east',
  },
  {
    id: 'catpope',
    title: 'His Holiness Mr. Whiskers',
    creator: 'Atelier del Gatto',
    description: 'Elected in a conclave of one. Has already excommunicated the vacuum cleaner.',
    source: '/art/catpope.webp',
    narration: '/audio/catpope.opus',
    position: [
      -17,
      2.65,
      -7.78,
    ],
    rotation: 0,
    width: 1.9,
    height: 2.53,
    hung: true,
    wallId: 'cabinet-north',
  },
  {
    id: 'segway',
    title: 'Bonaparte Crossing the Alps, Late for Brunch',
    creator: 'Jacques-Louis Davidson',
    description: 'The horse was unavailable. The Segway, however, was fully charged and deeply humiliated.',
    source: '/art/segway.webp',
    narration: '/audio/segway.opus',
    position: [
      -12.5,
      2.65,
      -7.78,
    ],
    rotation: 0,
    width: 3.1,
    height: 2.325,
    hung: true,
    wallId: 'cabinet-north',
  },
  {
    id: 'whale',
    title: 'Drawing Room with Unexpected Guest',
    creator: 'Dame Agatha Sprocket',
    description: 'The whale has been here since Tuesday. Nobody has mentioned it. The staff are being very British about it.',
    source: '/art/whale.webp',
    narration: '/audio/whale.opus',
    position: [
      -19.78,
      2.6,
      -2,
    ],
    rotation: 1.570_796_326_794_896_6,
    width: 3.2,
    height: 1.8,
    hung: true,
    wallId: 'cabinet-west',
  },
  {
    id: 'lighthouse',
    title: 'The Lighthouse at Frye Island',
    creator: 'Marlowe Crisp',
    description: 'For forty years sailors were guided home by a warm, salty, gently greasy beam. It worked, mostly.',
    source: '/art/lighthouse.webp',
    narration: '/audio/lighthouse.opus',
    position: [
      11,
      2.6,
      -7.78,
    ],
    rotation: 0,
    width: 1.9,
    height: 2.53,
    hung: true,
    wallId: 'afterhours-north',
  },
  {
    id: 'ambassador',
    title: 'The Ambassador',
    creator: 'Hans Holbein the App',
    description: 'Viewed head-on: a man of consequence. Viewed from the side: a consequence of being a man.',
    source: '/art/ambassador.webp',
    alternateSource: '/art/ambassador-side.webp',
    narration: '/audio/ambassador.opus',
    position: [
      16,
      2.6,
      -7.78,
    ],
    rotation: 0,
    width: 1.9,
    height: 2.53,
    hung: true,
    wallId: 'afterhours-north',
  },
  {
    id: 'beige',
    title: 'Untitled (Fifty Shades of Beige)',
    creator: 'Greige von Taupe',
    description: 'The single pink pixel is not a mistake. It is the artist screaming quietly, in the only way left.',
    source: '/art/beige.webp',
    narration: '/audio/beige.opus',
    position: [
      0,
      2.4,
      14.78,
    ],
    rotation: 3.141_592_653_589_793,
    width: 1.6,
    height: 1.6,
    hung: true,
    wallId: 'secret-south',
  },
]
