import type {Portrait} from './types.ts'

export const initialPortraits: Array<Portrait> = [
  {
    id: 'goose',
    title: 'His Unbothered Majesty',
    creator: 'Cornelius van Honk',
    description: 'A ruler of impeccable breeding and absolutely no qualifications. His foreign policy consists primarily of hissing.',
    source: '/art/goose.webp',
    narration: '/audio/goose.opus',
    position: [
      -3.6,
      2.5,
      -7.78,
    ],
    rotation: 0,
    width: 2.05,
    height: 2.05,
    hung: true,
    wallId: 'daydream-north',
  },
  {
    id: 'orange',
    title: 'A Slightly Larger Tomorrow',
    creator: 'The Department of Daydreams',
    description: 'The village had asked for a little more sunshine. The universe, as usual, misunderstood the brief.',
    source: '/art/orange.webp',
    narration: '/audio/orange.opus',
    position: [
      0,
      2.65,
      -7.78,
    ],
    rotation: 0,
    width: 2.7,
    height: 2.7,
    hung: true,
    wallId: 'daydream-north',
  },
  {
    id: 'dog',
    title: 'The Velvet Doge',
    creator: 'The Department of Good Dogs',
    description: 'A peaceful velvet pup with no appointments, no responsibilities and a deeply held belief that the entire sofa belongs to him.',
    source: '/art/dog.webp',
    narration: '/audio/dog.opus',
    position: [
      3.6,
      2.5,
      -7.78,
    ],
    rotation: 0,
    width: 2.05,
    height: 2.05,
    hung: true,
    wallId: 'daydream-north',
  },
  {
    id: 'wolf',
    title: 'Much Neon. Very Cosmic.',
    creator: 'The Department of Good Dogs',
    description: 'A galactic predator of pure neon fury. His cosmic authority is absolute, provided nobody mentions the vacuum cleaner.',
    source: '/art/wolf.webp',
    narration: '/audio/wolf.opus',
    position: [
      -4.5,
      2.5,
      7.78,
    ],
    rotation: 3.141_592_653_589_793,
    width: 2.05,
    height: 2.05,
    hung: true,
    wallId: 'daydream-south',
  },
  {
    id: 'tree',
    title: 'Rooted in Absolutely Nothing',
    creator: 'Sylvia Nimbus',
    description: 'A tree with excellent aspirations and a rather relaxed relationship with the ground. The gardener has requested a ladder.',
    source: '/art/tree.webp',
    narration: '/audio/tree.opus',
    position: [
      -7.78,
      2.5,
      -2.8,
    ],
    rotation: 1.570_796_326_794_896_6,
    width: 2.6,
    height: 2.6,
    hung: true,
    wallId: 'daydream-west',
  },
  {
    id: 'pigeon',
    title: 'Mona Coo Lisa',
    creator: 'Leonardo da Birb',
    description: 'Her enigmatic smile hides the fact she just stole your sandwich. A masterpiece of urban elegance and mild menace.',
    source: '/art/pigeon.png',
    narration: '/audio/pigeon.opus',
    position: [
      7.78,
      2.6,
      -2.8,
    ],
    rotation: -1.570_796_326_794_896_6,
    width: 1.45,
    height: 1.45,
    hung: true,
    wallId: 'daydream-east',
  },
  {
    id: 'toast',
    title: 'His Golden Crispness',
    creator: 'Imperial Court of Toast',
    description: 'The sovereign ruler of breakfast, anointed in salted butter and reigning over four slots of unyielding thermal perfection.',
    source: '/art/toast.webp',
    narration: '/audio/toast.opus',
    position: [
      19.78,
      2.6,
      -2,
    ],
    rotation: -1.570_796_326_794_896_6,
    width: 1.45,
    height: 1.45,
    hung: true,
    wallId: 'afterhours-east',
  },
  {
    id: 'cat',
    title: 'Cosmic Inconvenience',
    creator: 'Meow-ghelangelo',
    description: 'Proof that given infinite cosmic authority, a feline will still push entire clusters of stars off the counter simply to see them explode into supernovas.',
    source: '/art/cat.webp',
    narration: '/audio/cat.opus',
    position: [
      -17,
      2.65,
      -7.78,
    ],
    rotation: 0,
    width: 1.9,
    height: 1.9,
    hung: true,
    wallId: 'cabinet-north',
  },
  {
    id: 'fruit',
    title: 'The Algorithm Dreams of Fruit',
    creator: 'Generative Orchard No. 6',
    description: 'Synthetic produce contemplates whether humans can distinguish hunger from engagement. The banana has already accepted cookies.',
    source: '/art/fruit.webp',
    narration: '/audio/fruit.opus',
    position: [
      -12.5,
      2.65,
      -7.78,
    ],
    rotation: 0,
    width: 3.1,
    height: 2.06,
    hung: true,
    wallId: 'cabinet-north',
  },
  {
    id: 'ghosts',
    title: 'The Last Course Refuses to End',
    creator: 'Ectoplasmic Catering Collective',
    description: 'Dinner ran long. By approximately four centuries. No guest will admit who ordered the bottomless spectral linguine.',
    source: '/art/ghosts.avif',
    narration: '/audio/ghosts.opus',
    position: [
      -19.78,
      2.6,
      -2,
    ],
    rotation: 1.570_796_326_794_896_6,
    width: 2.7,
    height: 1.8,
    hung: true,
    wallId: 'cabinet-west',
  },
  {
    id: 'shrimp',
    title: 'Portrait of a Gentleman as Appetizer',
    creator: 'Rembrandt van Rijn-ish',
    description: 'He was a man of substance, of brine, and of cocktail sauce. History remembers only the sauce.',
    source: '/art/shrimp.webp',
    narration: '/audio/shrimp.opus',
    position: [
      11,
      2.6,
      -7.78,
    ],
    rotation: 0,
    width: 1.8975,
    height: 2.53,
    hung: true,
    wallId: 'afterhours-north',
  },
  {
    id: 'duck',
    title: 'Apotheosis of the Rubber Duck',
    creator: 'Michelangelo di Slop',
    description: 'The sacred bath toy ascends to the celestial heavens, forever untethered from bathtubs, soapsuds, and mortality.',
    source: '/art/duck.webp',
    narration: '/audio/duck.opus',
    position: [
      0,
      2.4,
      14.78,
    ],
    rotation: 3.141_592_653_589_793,
    width: 1.6,
    height: 1.6,
    hung: true,
    wallId: 'secret-south',
  },
  {
    id: 'bread',
    title: 'The Sourdough Soliloquy',
    creator: 'Jan van der Crumb',
    description: 'Born of wild yeast and existential dread, this loaf contemplated the fleeting cruelty of butter before meeting the serrated knife.',
    source: '/art/bread.webp',
    narration: '/audio/bread.opus',
    position: [
      16,
      2.6,
      -7.78,
    ],
    rotation: 0,
    width: 1.8,
    height: 1.8,
    hung: true,
    wallId: 'afterhours-north',
  },
  {
    id: 'frog',
    title: 'Mona Ribbit',
    creator: 'Leonardo da Pond',
    description: 'She smiles because she knows something you don’t – mostly where the flies are and why your pond is inferior.',
    source: '/art/frog.webp',
    narration: '/audio/frog.opus',
    position: [
      -14,
      2.5,
      7.78,
    ],
    rotation: 3.141_592_653_589_793,
    width: 1.8,
    height: 1.8,
    hung: true,
    wallId: 'cabinet-south',
  },
  {
    id: 'flower',
    title: 'Board and Lodging',
    creator: 'C. Nightbloom',
    description: 'The moths pay rent in dust. The furniture is pollen. Reservations are seasonal and spiritually non-refundable.',
    source: '/art/flower.webp',
    narration: '/audio/flower.opus',
    position: [
      14,
      2.6,
      7.78,
    ],
    rotation: 3.141_592_653_589_793,
    width: 1.6,
    height: 2,
    hung: true,
    wallId: 'afterhours-south',
  },
  {
    id: 'lobster',
    title: 'An Uninvited Tea Guest',
    creator: 'Salvador Deli',
    description: 'The tea is cold. The guest is shellfish. Nobody is having the afternoon they had imagined.',
    source: '/art/lobster.webp',
    narration: '/audio/lobster.opus',
    position: [
      4.5,
      2.5,
      7.78,
    ],
    rotation: 3.141_592_653_589_793,
    width: 2.05,
    height: 2.05,
    hung: true,
    wallId: 'daydream-south',
  },
]
