import type {KnotBay} from '#src/lib/knots/exhibition.ts'

import CanvasText from '#component/CanvasText'
import {knotPreviewX} from '#src/lib/knots/exhibition.ts'
import {useArtworkTexture} from '#src/lib/useArtworkTexture.ts'

/** Boards are generated by scripts/updateKnots.ts, not composed during gameplay. */
export default function KnotPreviewSign({bay}: {bay: KnotBay}) {
  const {texture} = useArtworkTexture(bay.overview)
  const aspect = texture ? texture.image.width / texture.image.height : 1280 / 732
  const width = Math.min(4.8, 2.75 * aspect)
  const height = width / aspect
  return <group name={`preview-${bay.model}`} position={[knotPreviewX, 1.5, 0]} rotation={[0, Math.PI / 2, 0]}>
    <mesh name={`preview-image-${bay.model}`}>
      <planeGeometry args={[width, height]}/>
      <meshBasicNodeMaterial map={texture} color={texture ? '#ffffff' : '#122029'} toneMapped={false}/>
    </mesh>
    <CanvasText text={`${bay.labels} · ${bay.title}`} width={4.8} height={0.32} position={[0, height / 2 + 0.28, 0]} color="#17202b" fontWeight={600}/>
  </group>
}
