import {expect, mock, test} from 'bun:test'

import RetainedLifetime from '../src/RetainedLifetime.ts'

test('effect replay retains the resource and final unmount disposes it once', async () => {
  const dispose = mock(() => {})
  const lifetime = new RetainedLifetime(dispose)
  const first = lifetime.retain()
  first[Symbol.dispose]()
  const second = lifetime.retain()
  await Promise.resolve()
  expect(dispose).not.toHaveBeenCalled()
  second[Symbol.dispose]()
  expect(dispose).not.toHaveBeenCalled()
  await Promise.resolve()
  expect(dispose).toHaveBeenCalledTimes(1)
  second[Symbol.dispose]()
  await Promise.resolve()
  expect(dispose).toHaveBeenCalledTimes(1)
  expect(() => lifetime.retain()).toThrow('disposed')
})
test('replacement releases the old lifetime without disposing the new resource', async () => {
  const disposeOld = mock(() => {})
  const disposeNew = mock(() => {})
  const old = new RetainedLifetime(disposeOld)
  const next = new RetainedLifetime(disposeNew)
  const releaseOld = old.retain()
  releaseOld[Symbol.dispose]()
  const releaseNext = next.retain()
  await Promise.resolve()
  expect(disposeOld).toHaveBeenCalledTimes(1)
  expect(disposeNew).not.toHaveBeenCalled()
  releaseNext[Symbol.dispose]()
  await Promise.resolve()
  expect(disposeNew).toHaveBeenCalledTimes(1)
})
test('multiple leases keep the resource alive until every lease is released', async () => {
  const dispose = mock(() => {})
  const lifetime = new RetainedLifetime(dispose)
  const first = lifetime.retain()
  const second = lifetime.retain()
  first[Symbol.dispose]()
  first[Symbol.dispose]()
  await Promise.resolve()
  expect(dispose).not.toHaveBeenCalled()
  second[Symbol.dispose]()
  await Promise.resolve()
  expect(dispose).toHaveBeenCalledTimes(1)
})
test('leases participate in native using scopes', async () => {
  const dispose = mock(() => {})
  const lifetime = new RetainedLifetime(dispose)
  {
    using lease = lifetime.retain()
    expect(typeof lease[Symbol.dispose]).toBe('function')
  }
  expect(dispose).not.toHaveBeenCalled()
  await Promise.resolve()
  expect(dispose).toHaveBeenCalledTimes(1)
})
