import rule from '../src/rules/prefer-branch-component.ts'
import {branchImport, ruleTester} from './ruleTester.ts'

ruleTester.run('prefer-branch-component', rule, {
  valid: [
    'const value = ok ? 1 : 2',
    'const view = <div className={ok ? "active" : "idle"} />',
    'const view = <div>{count && <Content />}</div>',
    'const view = <div>{value || <Content />}</div>',
    'const view = <div>{value ?? <Content />}</div>',
    'const view = <div>{value && 1}</div>',
    'const view = <div>{Boolean(value) && "text"}</div>',
    'function view(Boolean) { return Boolean(value) && <Content /> }',
    `${branchImport}const view = <Branch if={ok}><Content /></Branch>`,
  ],
  invalid: [
    ...[
      ['const view = ok ? <Content /> : null', 'const view = <Branch if={ok}><Content /></Branch>'],
      ['const view = ok ? <Content /> : <Fallback />', 'const view = <Branch if={ok} else={<Fallback />}><Content /></Branch>'],
      ['const view = ok ? null : <Fallback />', 'const view = <Branch not={ok}><Fallback /></Branch>'],
      ['const view = !ok ? <Content /> : null', 'const view = <Branch if={!ok}><Content /></Branch>'],
      ['const view = ok ? <><Content /><Other /></> : null', 'const view = <Branch if={ok}><><Content /><Other /></></Branch>'],
      ['const view = <div>{ok ? <Content /> : null}</div>', 'const view = <div><Branch if={ok}><Content /></Branch></div>'],
      ['const view = <>{ok ? "yes" : "no"}</>', 'const view = <><Branch if={ok} else={"no"}>{"yes"}</Branch></>'],
      ['const view = <>{ok ? 1 : 0}</>', 'const view = <><Branch if={ok} else={0}>{1}</Branch></>'],
      ['const view = ok ? <Content /> : false', 'const view = <Branch if={ok} else={false}><Content /></Branch>'],
      ['const view = <>{!!ok && <Content />}</>', 'const view = <><Branch if={!!ok}><Content /></Branch></>'],
      ['const view = count > 0 && <Content />', 'const view = <Branch if={count > 0}><Content /></Branch>'],
      ['const view = Boolean(ok) && <Content />', 'const view = <Branch if={Boolean(ok)}><Content /></Branch>'],
      ['const view = (count > 0 && !busy) && <Content />', 'const view = <Branch if={count > 0 && !busy}><Content /></Branch>'],
      ['const ok: boolean = true; const view = ok && <Content />', 'const ok: boolean = true; const view = <Branch if={ok}><Content /></Branch>'],
      ['const view = (ok as boolean) && <Content />', 'const view = <Branch if={ok as boolean}><Content /></Branch>'],
      ['function view(ok: boolean) { return ok && <Content /> }', 'function view(ok: boolean) { return <Branch if={ok}><Content /></Branch> }'],
      ['const view = (tick(), ok) ? <Content /> : null', 'const view = <Branch if={(tick(), ok)}><Content /></Branch>'],
      ['const view = ok ? (<Content />) : null', 'const view = <Branch if={ok}><Content /></Branch>'],
      ['const view = <>{/* keep */ ok ? <Content /> : null}</>', 'const view = <>{/* keep */ <Branch if={ok}><Content /></Branch>}</>'],
      ['const view = ok ? <div>{/* keep */}<Content /></div> : null', 'const view = <Branch if={ok}><div>{/* keep */}<Content /></div></Branch>'],
      ['const view = ok ? <Content value={value} /> : null', 'const view = <Branch if={ok}><Content value={value} /></Branch>'],
      ['const view = ok ? <Content onClick={() => run()} /> : null', 'const view = <Branch if={ok}><Content onClick={() => run()} /></Branch>'],
      ['const view = ok ? <div style={{display: "flex"}} /> : null', 'const view = <Branch if={ok}><div style={{display: "flex"}} /></Branch>'],
    ].map(([code, output]) => ({
      code: branchImport + code,
      output: branchImport + output,
      errors: [{messageId: 'prefer' as const}],
    })),
    {
      code: 'const view = ok ? <Content /> : null',
      output: "import BranchComponent from 'branch-component'\nconst view = <BranchComponent if={ok}><Content /></BranchComponent>",
      errors: [{messageId: 'prefer'}],
    },
    {
      code: '"use client";\nconst view = ok ? <Content /> : null',
      output: '"use client";\nimport BranchComponent from \'branch-component\'\nconst view = <BranchComponent if={ok}><Content /></BranchComponent>',
      errors: [{messageId: 'prefer'}],
    },
    {
      code: '#!/usr/bin/env node\n// keep\nconst view = ok ? <Content /> : null',
      output: '#!/usr/bin/env node\n// keep\nimport BranchComponent from \'branch-component\'\nconst view = <BranchComponent if={ok}><Content /></BranchComponent>',
      errors: [{messageId: 'prefer'}],
    },
    {
      code: 'import Other from "other";\nconst view = ok ? <Content /> : null',
      output: 'import BranchComponent from "branch-component";\nimport Other from "other";\nconst view = <BranchComponent if={ok}><Content /></BranchComponent>',
      errors: [{messageId: 'prefer'}],
    },
    {
      code: 'const view = (BranchComponent) => ok ? <Content /> : null',
      output: "import BranchComponent2 from 'branch-component'\nconst view = (BranchComponent) => <BranchComponent2 if={ok}><Content /></BranchComponent2>",
      errors: [{messageId: 'prefer'}],
    },
    {
      code: `${branchImport}const view = Branch => ok ? <Content /> : null`,
      output: `import BranchComponent from 'branch-component';\n${branchImport}const view = Branch => <BranchComponent if={ok}><Content /></BranchComponent>`,
      errors: [{messageId: 'prefer'}],
    },
    ...[
      ["import B from 'branch-component'; ", 'B'],
      ["import {default as B} from 'branch-component'; ", 'B'],
      ["import * as branches from 'branch-component'; ", 'branches.default'],
    ].map(([prefix, name]) => ({
      code: `${prefix}const view = ok ? <Content /> : null`,
      output: `${prefix}const view = <${name} if={ok}><Content /></${name}>`,
      errors: [{messageId: 'prefer' as const}],
    })),
    ...[
      'const view = user ? <Content name={user.name} /> : null',
      'const view = ok ? <Content value={expensive()} /> : null',
      'const view = ok ? <Content {...props} /> : null',
      'const view = ok ? <Content /> : fallback()',
      'const view = ok ? <div>{expensive()}</div> : null',
      'const view = ok ? <div>{count++}</div> : null',
      'const view = ok ? <UI.Content /> : null',
      'const view = ok /* keep */ ? <Content /> : null',
      'const view = ok ? /* keep */ <Content /> : null',
      'const view = ok ? <Content /> : /* keep */ null',
      'const view = ok ? <div>{a + b}</div> : null',
      'const view = ok ? <div>{`${value}`}</div> : null',
    ].map(code => ({
      code: branchImport + code,
      output: null,
      errors: [{messageId: 'prefer' as const}],
    })),
    {
      code: 'const view = ok ? <Content /> : null',
      languageOptions: {parserOptions: {sourceType: 'script'}},
      output: null,
      errors: [{messageId: 'prefer'}],
    },
  ],
})
